name: gift_manager
description: Manage your gifts
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  collection: ^1.17.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  either_dart: ^0.3.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_pretty_dio_logger: ^2.0.3
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  json_annotation: ^4.8.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.17

dev_dependencies:
  build_runner: ^2.3.3
  carapacik_lints: ^1.3.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/